site_name: 'OGC Testbed 16 - Terradue DAPA demonstrator'
theme:
    name: 'material'
    logo: imgs/TERRADUE_Icon_3.png
    favicon: img/TERRADUE_Icon_3.png
    palette:
       primary: white
       accent: teal
nav:
    - Welcome: index.md
    - Getting started: started.md
    - API documentation: 
        - Capabilities: capabilities.md
        - Collections: collections.md
        - Processes: processes.md
    
plugins:
  - mknotebooks
  - search
  
markdown_extensions:
    - codehilite:
        linenums: true
        guess_lang: false
    - footnotes
    - toc:
        permalink: true
    - pymdownx.details
    - admonition
    - pymdownx.tabbed
    - pymdownx.superfences    
